import React from 'react';

/**
 * Renders normalized audio peaks generated by the BullMQ background worker.
 * Indicates live playback progress along the waveform.
 */
const WaveformBar = ({ peaks = [], progress = 0, isPlaying = false, onClickSeek }) => {
  // Fallback default sample peaks if track is still processing in BullMQ
  const displayPeaks = peaks.length > 0 
    ? peaks 
    : [0.3, 0.5, 0.8, 0.4, 0.6, 0.9, 0.7, 0.5, 0.4, 0.8, 0.6, 0.3];

  return (
    <div 
      className="flex items-center gap-[3px] h-9 px-2 cursor-pointer group"
      onClick={(e) => {
        if (!onClickSeek) return;
        const rect = e.currentTarget.getBoundingClientRect();
        const clickRatio = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
        onClickSeek(clickRatio);
      }}
      title="Click to seek along waveform"
    >
      {displayPeaks.map((peak, idx) => {
        const barRatio = idx / displayPeaks.length;
        const isPast = barRatio <= progress;

        return (
          <div
            key={idx}
            style={{ height: `${Math.max(15, peak * 100)}%` }}
            className={`w-1 rounded-full transition-all duration-150 ${
              isPast
                ? 'bg-emerald-400 group-hover:bg-emerald-300'
                : 'bg-slate-700 group-hover:bg-slate-600'
            } ${isPlaying && isPast ? 'opacity-100' : 'opacity-85'}`}
          />
        );
      })}
    </div>
  );
};

export default WaveformBar;